POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "user1test",
    "password": "1234"
}


###


POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MDMyMDk2MiwiaWF0IjoxNzM5NzE2MTYyLCJqdGkiOiI0MjIzMDM2MGNlZGE0OTBiYjliOWFmZjg1ZjlhNGYzMyIsInVzZXJfaWQiOjJ9.8nYQ2U3gA5mxNfvm0uiENbqAmWXQhc4GRwa-hIUR93I"
}