services:
  django_backend:
    build:
      context: ./django/project
    container_name: django_backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=True

  vue_frontend:
    build:
      context: ./one_page2
    container_name: vue_frontend
    ports:
      - "80:80"
      # environment:
      # - API_URL=http://django_backend:8000
      # where is used api url change to process.env.API_URL;

      # db:
      #   image: postgres:15
      #   container_name: postgres
      #   restart: always
      #   environment:
      #     POSTGRES_USER: admin
      #     POSTGRES_PASSWORD: Password1234
      #     POSTGRES_DB: flights_data_db
      #   ports:
      #     - "5432:5432"
      #   volumes:
      #     - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Password1234
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sender:
    build:
      context: ./rabbitmq-vue
    container_name: producer
    ports:
      - "3000:3000"
    restart: always

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    ports:
      - "8080:8080"
    restart: always


volumes:
  db_data:
  rabbitmq_data: