services:
  django_backend:
    build:
      context: ./django/first_project
    container_name: django_backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=True 

  vue_frontend:
    build:
      context: ./one_page2
    container_name: vue_frontend
    ports:
      - "80:80"
    # environment:
      # - API_URL=http://django_backend:8000
      # where is used api url change to process.env.API_URL;
