# Generated by Django 5.1.3 on 2024-11-18 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_status_onepisode_anime_onepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='onEpisode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
