# Generated by Django 4.2.17 on 2025-01-12 22:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('altitude', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('track', models.FloatField(null=True)),
                ('rc', models.FloatField(blank=True, null=True)),
                ('epu', models.FloatField(blank=True, null=True)),
                ('vepu', models.FloatField(blank=True, null=True)),
                ('hfomr', models.FloatField(blank=True, null=True)),
                ('vfomr', models.FloatField(blank=True, null=True)),
                ('hex_code', models.CharField(blank=True, unique=True)),
                ('icao_id', models.CharField(max_length=10, null=True)),
                ('call_sign', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, null=True)),
                ('time_received', models.DateTimeField(null=True)),
                ('plane_distance', models.FloatField(blank=True, null=True)),
                ('PositionData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positionData', to='first_part.positiondata')),
            ],
        ),
    ]
