# Generated by Django 4.2.17 on 2025-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_part', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_name'], name='indx_place_name'),
        ),
        migrations.AddIndex(
            model_name='positiondata',
            index=models.Index(fields=['hex_code'], name='indx_hex_code'),
        ),
    ]
