# Generated by Django 4.2.17 on 2024-12-18 17:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('time_received', models.DateTimeField()),
                ('plane_distance', models.FloatField(blank=True, null=True)),
                ('test_field1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('track', models.FloatField()),
                ('rc', models.FloatField(blank=True, null=True)),
                ('epu', models.FloatField(blank=True, null=True)),
                ('vepu', models.FloatField(blank=True, null=True)),
                ('hfomr', models.FloatField(blank=True, null=True)),
                ('vfomr', models.FloatField(blank=True, null=True)),
                ('hex_code', models.CharField(blank=True, null=True)),
                ('icao_id', models.CharField(max_length=10, unique=True)),
                ('call_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('test_field2', models.FloatField()),
                ('test', models.CharField()),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='first_part.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
